import { ICropStageTemplate } from "@/types/crop-schedule";

export const AGRONOMY_CROP_TEMPLATES: Record<string, ICropStageTemplate[]> = {
  Wheat: [
    {
      stageIndex: 0,
      stageName: "Sowing & Seed Treatment",
      activityType: "Sowing",
      offsetDaysStart: 0,
      offsetDaysEnd: 3,
      title: "Sowing & Trichoderma Seed Treatment",
      description: "Sow seeds at 4-5 cm depth with recommended basal NPK fertilizer dose.",
      recommendedAction: "Apply 50% Nitrogen and 100% Phosphorus & Potassium at sowing.",
    },
    {
      stageIndex: 1,
      stageName: "Crown Root Initiation (CRI)",
      activityType: "Irrigation",
      offsetDaysStart: 20,
      offsetDaysEnd: 25,
      title: "First Irrigation (CRI Stage)",
      description: "Critical first irrigation stage. Water stress at CRI severely impacts root formation.",
      recommendedAction: "Provide light irrigation. Ensure waterlogging does not occur.",
    },
    {
      stageIndex: 2,
      stageName: "Tillering & Top Dressing",
      activityType: "Fertilization",
      offsetDaysStart: 30,
      offsetDaysEnd: 35,
      title: "Urea Top Dressing Application",
      description: "Apply second dose of Nitrogen to encourage healthy tillering.",
      recommendedAction: "Broadcast 25% Nitrogen (Urea) right after soil moisture stabilizes.",
    },
    {
      stageIndex: 3,
      stageName: "Jointing & Weed Control",
      activityType: "Weeding",
      offsetDaysStart: 40,
      offsetDaysEnd: 45,
      title: "Broadleaf & Grassy Weed Control",
      description: "Inspect field for Phalaris minor and broadleaf weeds.",
      recommendedAction: "Manual weeding or selective post-emergence herbicide spray.",
    },
    {
      stageIndex: 4,
      stageName: "Booting & Flowering Stage",
      activityType: "Irrigation",
      offsetDaysStart: 60,
      offsetDaysEnd: 65,
      title: "Second Irrigation (Booting Stage)",
      description: "Maintain adequate soil moisture during earhead emergence.",
      recommendedAction: "Irrigate field lightly. Check for early yellow rust symptoms.",
    },
    {
      stageIndex: 5,
      stageName: "Flag Leaf Rust Protection",
      activityType: "Pest Control",
      offsetDaysStart: 75,
      offsetDaysEnd: 80,
      title: "Fungal Disease & Rust Inspection",
      description: "Inspect flag leaves for stripe rust, yellow rust, or aphid clusters.",
      recommendedAction: "Apply propiconazole or bio-pesticide spray if brown spots appear.",
    },
    {
      stageIndex: 6,
      stageName: "Milk & Dough Stage",
      activityType: "Crop Inspection",
      offsetDaysStart: 95,
      offsetDaysEnd: 100,
      title: "Grain Filling Inspection",
      description: "Monitor grain firmness as crop transitions to golden yellow.",
      recommendedAction: "Stop irrigation 10-15 days before expected harvest.",
    },
    {
      stageIndex: 7,
      stageName: "Harvest & Threshing",
      activityType: "Harvest",
      offsetDaysStart: 115,
      offsetDaysEnd: 125,
      title: "Crop Harvesting & Threshing",
      description: "Harvest when grain moisture drops below 12% and stalks turn dry golden.",
      recommendedAction: "Harvest during clear weather. Store grains in dry, ventilated bags.",
    },
  ],
  Paddy: [
    {
      stageIndex: 0,
      stageName: "Sowing / Nursery Preparation",
      activityType: "Sowing",
      offsetDaysStart: 0,
      offsetDaysEnd: 3,
      title: "Paddy Seed Treatment & Nursery Bed Sowing",
      description: "Treat seeds with Pseudomonas / Carbendazim and sow in raised beds.",
      recommendedAction: "Maintain moist nursery soil for uniform germination.",
    },
    {
      stageIndex: 1,
      stageName: "Transplanting Stage",
      activityType: "Field Preparation",
      offsetDaysStart: 20,
      offsetDaysEnd: 25,
      title: "Field Puddling & Seedling Transplanting",
      description: "Transplant 2-3 seedlings per hill at 2-3 cm depth.",
      recommendedAction: "Maintain 2-5 cm standing water layer in puddle field.",
    },
    {
      stageIndex: 2,
      stageName: "Active Tillering & Nitrogen Top Dressing",
      activityType: "Fertilization",
      offsetDaysStart: 35,
      offsetDaysEnd: 40,
      title: "Nitrogen (Urea) & Zinc Application",
      description: "Apply first split of Urea along with Zinc Sulphate.",
      recommendedAction: "Broadcast Urea when standing water is minimal.",
    },
    {
      stageIndex: 3,
      stageName: "Stem Borer & Leaf Folder Protection",
      activityType: "Pest Control",
      offsetDaysStart: 50,
      offsetDaysEnd: 55,
      title: "Pest Inspection (Dead Hearts / Rolling Leaves)",
      description: "Inspect tiller bases for yellow stem borer or leaf folder caterpillars.",
      recommendedAction: "Deploy pheromone traps or neem-based pesticide spray.",
    },
    {
      stageIndex: 4,
      stageName: "Panicle Initiation & Flowering",
      activityType: "Irrigation",
      offsetDaysStart: 70,
      offsetDaysEnd: 75,
      title: "Critical Panicle Water Management",
      description: "Keep 5 cm standing water continuously during flowering.",
      recommendedAction: "Ensure field does not dry out during panicle emergence.",
    },
    {
      stageIndex: 5,
      stageName: "Grain Filling & Drainage",
      activityType: "Crop Inspection",
      offsetDaysStart: 95,
      offsetDaysEnd: 100,
      title: "Pre-Harvest Field Drainage",
      description: "Drain standing water to encourage uniform grain hardening.",
      recommendedAction: "Drain field 10 days prior to combine harvesting.",
    },
    {
      stageIndex: 6,
      stageName: "Harvesting & Threshing",
      activityType: "Harvest",
      offsetDaysStart: 115,
      offsetDaysEnd: 125,
      title: "Paddy Harvesting & Threshing",
      description: "Harvest when 80-85% of panicles turn straw yellow.",
      recommendedAction: "Thresh immediately and dry grains to 13% moisture.",
    },
  ],
  Cotton: [
    {
      stageIndex: 0,
      stageName: "Sowing & Basal Dose",
      activityType: "Sowing",
      offsetDaysStart: 0,
      offsetDaysEnd: 3,
      title: "Bt Cotton Sowing & Basal NPK",
      description: "Sow seeds at 3-5 cm depth maintaining 90x60 cm spacing.",
      recommendedAction: "Apply full Phosphorus & Potassium with 25% Nitrogen.",
    },
    {
      stageIndex: 1,
      stageName: "First Weeding & Thinning",
      activityType: "Weeding",
      offsetDaysStart: 20,
      offsetDaysEnd: 25,
      title: "Inter-cultivation & Thinning",
      description: "Retain one healthy seedling per hill and clear early weeds.",
      recommendedAction: "Perform hoeing to aerate root zone.",
    },
    {
      stageIndex: 2,
      stageName: "Squaring & Top Dressing",
      activityType: "Fertilization",
      offsetDaysStart: 40,
      offsetDaysEnd: 45,
      title: "Urea Top Dressing at Squaring",
      description: "Apply second split of Nitrogen before flower bud initiation.",
      recommendedAction: "Irrigate lightly following fertilizer application.",
    },
    {
      stageIndex: 3,
      stageName: "Sucking Pest & Bollworm Protection",
      activityType: "Pest Control",
      offsetDaysStart: 60,
      offsetDaysEnd: 65,
      title: "Whitefly, Thrips & Pink Bollworm Inspection",
      description: "Inspect lower leaf surfaces for sucking pests or pink bollworm larvae.",
      recommendedAction: "Spray yellow sticky traps or recommended biopesticides.",
    },
    {
      stageIndex: 4,
      stageName: "Peak Flowering & Boll Formation",
      activityType: "Irrigation",
      offsetDaysStart: 85,
      offsetDaysEnd: 90,
      title: "Boll Formation Water Management",
      description: "Maintain consistent moisture to reduce flower & boll shedding.",
      recommendedAction: "Avoid water stress during boll development.",
    },
    {
      stageIndex: 5,
      stageName: "Boll Opening & Picking",
      activityType: "Harvest",
      offsetDaysStart: 130,
      offsetDaysEnd: 150,
      title: "First Cotton Picking",
      description: "Pick fully opened, dry cotton bolls in clear sunny weather.",
      recommendedAction: "Keep picked cotton free from dry leaves and trash.",
    },
  ],
  Tomato: [
    {
      stageIndex: 0,
      stageName: "Transplanting",
      activityType: "Sowing",
      offsetDaysStart: 0,
      offsetDaysEnd: 2,
      title: "Tomato Seedling Transplanting",
      description: "Transplant 25-30 day old healthy seedlings on raised ridges.",
      recommendedAction: "Drench roots with bio-fungicide during transplanting.",
    },
    {
      stageIndex: 1,
      stageName: "Staking & Gap Filling",
      activityType: "Field Preparation",
      offsetDaysStart: 10,
      offsetDaysEnd: 12,
      title: "Bamboo Staking & Tying",
      description: "Erect bamboo stakes to support indeterminate tomato vines.",
      recommendedAction: "Tie main stems gently using twine.",
    },
    {
      stageIndex: 2,
      stageName: "Vegetative NPK Boost",
      activityType: "Fertilization",
      offsetDaysStart: 25,
      offsetDaysEnd: 30,
      title: "NPK & Micronutrient Top Dressing",
      description: "Apply balanced NPK dose along with Calcium Boron drip.",
      recommendedAction: "Incorporate fertilizer near root drip line.",
    },
    {
      stageIndex: 3,
      stageName: "Blight & Fruit Borer Protection",
      activityType: "Pest Control",
      offsetDaysStart: 45,
      offsetDaysEnd: 50,
      title: "Early Blight & Fruit Borer Spray",
      description: "Inspect leaves for concentric dark rings or bored fruits.",
      recommendedAction: "Apply preventive Copper Oxychloride or neem spray.",
    },
    {
      stageIndex: 4,
      stageName: "Peak Harvesting Picking Cycle",
      activityType: "Harvest",
      offsetDaysStart: 75,
      offsetDaysEnd: 90,
      title: "First Fruit Picking & Sorting",
      description: "Harvest mature red/breaker stage tomatoes every 3-4 days.",
      recommendedAction: "Store in plastic crates in cool shaded area.",
    },
  ],
};

// Generic fallback template generator for crops not explicitly mapped
export function getGenericCropTemplate(cropName: string): ICropStageTemplate[] {
  return [
    {
      stageIndex: 0,
      stageName: "Sowing & Planting",
      activityType: "Sowing",
      offsetDaysStart: 0,
      offsetDaysEnd: 3,
      title: `${cropName} Sowing / Planting`,
      description: `Sow seeds or plant seedlings of ${cropName} with basal fertilizer application.`,
      recommendedAction: "Ensure proper seed treatment and moist seedbed condition.",
    },
    {
      stageIndex: 1,
      stageName: "Initial Irrigation & Establishment",
      activityType: "Irrigation",
      offsetDaysStart: 15,
      offsetDaysEnd: 20,
      title: `First Irrigation & Field Inspection`,
      description: `Provide initial moisture to support early root establishment.`,
      recommendedAction: "Check germination percentage and fill gaps if necessary.",
    },
    {
      stageIndex: 2,
      stageName: "Nutrient Top Dressing",
      activityType: "Fertilization",
      offsetDaysStart: 30,
      offsetDaysEnd: 35,
      title: `Vegetative Growth Fertilizer Application`,
      description: `Apply top-dressing Nitrogen/NPK fertilizer to boost vine/stalk growth.`,
      recommendedAction: "Apply fertilizer when soil is moist.",
    },
    {
      stageIndex: 3,
      stageName: "Weed Control & Crop Protection",
      activityType: "Pest Control",
      offsetDaysStart: 45,
      offsetDaysEnd: 50,
      title: `Weed & Pest Inspection`,
      description: `Inspect field for foliage pests, chewing insects, or foliar spots.`,
      recommendedAction: "Perform manual weeding and spray bio-pesticide if threshold is crossed.",
    },
    {
      stageIndex: 4,
      stageName: "Flowering / Fruit Formation",
      activityType: "Irrigation",
      offsetDaysStart: 65,
      offsetDaysEnd: 70,
      title: `Flowering Stage Moisture Management`,
      description: `Maintain optimal soil moisture during flowering and yield formation.`,
      recommendedAction: "Prevent extreme dry-wet moisture fluctuations.",
    },
    {
      stageIndex: 5,
      stageName: "Harvesting",
      activityType: "Harvest",
      offsetDaysStart: 95,
      offsetDaysEnd: 110,
      title: `${cropName} Crop Harvesting`,
      description: `Harvest mature produce during favorable dry weather.`,
      recommendedAction: "Clean, grade, and record total yield volume in Harvest Logs.",
    },
  ];
}

export function getCropStageTemplates(cropName: string): ICropStageTemplate[] {
  const normalized = (cropName || "").trim();
  for (const [key, templates] of Object.entries(AGRONOMY_CROP_TEMPLATES)) {
    if (key.toLowerCase() === normalized.toLowerCase() || normalized.toLowerCase().includes(key.toLowerCase())) {
      return templates;
    }
  }
  return getGenericCropTemplate(normalized || "Crop");
}
