import connectDB from "@/lib/mongodb";
import AgricultureCenter from "@/models/AgricultureCenter";

export const VERIFIED_AGRICULTURE_CENTERS = [
  {
    name: "Krishi Vigyan Kendra (KVK) Narayangaon",
    type: "KVK",
    address: "Baburaoji Gholap College Campus, Narayangaon, Taluka Junnar, Pune, Maharashtra 410504",
    district: "Pune",
    state: "Maharashtra",
    pincode: "410504",
    phone: "02132-242255",
    email: "kvknarayangaon@gmail.com",
    website: "https://kvknarayangaon.com",
    location: {
      type: "Point" as const,
      coordinates: [73.9782, 19.1171], // [longitude, latitude]
    },
    officialSource: "ICAR - ATARI Pune / Gramonnati Mandal",
    sourceUrl: "https://kvk.icar.gov.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "Krishi Vigyan Kendra (KVK) Baramati",
    type: "KVK",
    address: "Agricultural Development Trust Campus, Shardanagar, Baramati, Pune, Maharashtra 413115",
    district: "Pune",
    state: "Maharashtra",
    pincode: "413115",
    phone: "02112-255227",
    email: "kvkbaramati@yahoo.com",
    website: "https://kvkbaramati.com",
    location: {
      type: "Point" as const,
      coordinates: [74.5772, 18.1565],
    },
    officialSource: "ICAR - Agricultural Technology Application Research Institute (ATARI)",
    sourceUrl: "https://kvk.icar.gov.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "ICAR - Indian Agricultural Research Institute (IARI) Regional Station",
    type: "University",
    address: "Agricultural College Campus, Shivajinagar, Pune, Maharashtra 411005",
    district: "Pune",
    state: "Maharashtra",
    pincode: "411005",
    phone: "020-25537330",
    email: "head_pune@iari.res.in",
    website: "https://iari.res.in",
    location: {
      type: "Point" as const,
      coordinates: [73.8512, 18.5314],
    },
    officialSource: "ICAR - Indian Agricultural Research Institute",
    sourceUrl: "https://iari.res.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "District Superintending Agriculture Office (DAO) Pune",
    type: "GovtOffice",
    address: "Central Building, Agarkar Nagar, Near Railway Station, Pune, Maharashtra 411001",
    district: "Pune",
    state: "Maharashtra",
    pincode: "411001",
    phone: "020-26123456",
    email: "sao.pune@maharashtra.gov.in",
    website: "https://krishi.maharashtra.gov.in",
    location: {
      type: "Point" as const,
      coordinates: [73.8742, 18.5284],
    },
    officialSource: "Department of Agriculture, Govt of Maharashtra",
    sourceUrl: "https://krishi.maharashtra.gov.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "Government District Soil Testing Laboratory Pune",
    type: "SoilLab",
    address: "College of Agriculture Campus, Shivajinagar, Pune, Maharashtra 411005",
    district: "Pune",
    state: "Maharashtra",
    pincode: "411005",
    phone: "020-25537021",
    email: "",
    website: "https://soilhealth.dac.gov.in",
    location: {
      type: "Point" as const,
      coordinates: [73.8505, 18.5308],
    },
    officialSource: "Soil Health Card Scheme, Ministry of Agriculture, Govt of India",
    sourceUrl: "https://soilhealth.dac.gov.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "Mahatma Phule Krishi Vidyapeeth (MPKV) Central Campus",
    type: "University",
    address: "MPKV Campus, Rahuri, Ahmednagar, Maharashtra 413722",
    district: "Ahmednagar",
    state: "Maharashtra",
    pincode: "413722",
    phone: "02426-243208",
    email: "registrar.mpkv@gov.in",
    website: "https://mpkv.ac.in",
    location: {
      type: "Point" as const,
      coordinates: [74.6469, 19.3402],
    },
    officialSource: "Mahatma Phule Krishi Vidyapeeth, Govt of Maharashtra",
    sourceUrl: "https://mpkv.ac.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "Krishi Vigyan Kendra (KVK) Yashwantrao Chavan Maharashtra Open University",
    type: "KVK",
    address: "YCMOU Campus, Dindori Road, Nashik, Maharashtra 422222",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422222",
    phone: "0253-2230700",
    email: "kvknashik@yahoo.com",
    website: "https://ycmou.ac.in",
    location: {
      type: "Point" as const,
      coordinates: [73.7714, 20.0635],
    },
    officialSource: "ICAR - ATARI Pune / YCMOU",
    sourceUrl: "https://kvk.icar.gov.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "District Superintending Agriculture Office (DAO) Nashik",
    type: "GovtOffice",
    address: "Old Agra Road, Opposite District Collectorate, Nashik, Maharashtra 422001",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422001",
    phone: "0253-2578912",
    email: "sao.nashik@maharashtra.gov.in",
    website: "https://krishi.maharashtra.gov.in",
    location: {
      type: "Point" as const,
      coordinates: [73.7885, 20.0022],
    },
    officialSource: "Department of Agriculture, Govt of Maharashtra",
    sourceUrl: "https://krishi.maharashtra.gov.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "Krishi Vigyan Kendra (KVK) Solapur",
    type: "KVK",
    address: "Khed, Near State Highway 148, Solapur, Maharashtra 413006",
    district: "Solapur",
    state: "Maharashtra",
    pincode: "413006",
    phone: "0217-2373200",
    email: "kvksolapur@gmail.com",
    website: "",
    location: {
      type: "Point" as const,
      coordinates: [75.9064, 17.6599],
    },
    officialSource: "ICAR - ATARI Pune",
    sourceUrl: "https://kvk.icar.gov.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "Krishi Vigyan Kendra (KVK) Latur",
    type: "KVK",
    address: "Additional MIDC Industrial Area, Latur, Maharashtra 413531",
    district: "Latur",
    state: "Maharashtra",
    pincode: "413531",
    phone: "02382-221450",
    email: "",
    website: "",
    location: {
      type: "Point" as const,
      coordinates: [76.5813, 18.4088],
    },
    officialSource: "ICAR - ATARI Pune",
    sourceUrl: "https://kvk.icar.gov.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "Krishi Vigyan Kendra (KVK) Central Institute for Cotton Research",
    type: "KVK",
    address: "ICAR - CICR Campus, Panjri, Wardha Road, Nagpur, Maharashtra 441108",
    district: "Nagpur",
    state: "Maharashtra",
    pincode: "441108",
    phone: "07103-275538",
    email: "kvknagpur@cicr.org.in",
    website: "https://cicr.org.in",
    location: {
      type: "Point" as const,
      coordinates: [79.0521, 21.0345],
    },
    officialSource: "ICAR - Central Institute for Cotton Research (CICR)",
    sourceUrl: "https://cicr.org.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "ICAR - Indian Agricultural Research Institute (IARI) Main Campus",
    type: "University",
    address: "Pusa Institute Campus, Pusa, New Delhi 110012",
    district: "New Delhi",
    state: "Delhi",
    pincode: "110012",
    phone: "011-25843375",
    email: "director@iari.res.in",
    website: "https://iari.res.in",
    location: {
      type: "Point" as const,
      coordinates: [77.1597, 28.6369],
    },
    officialSource: "ICAR - Indian Agricultural Research Institute",
    sourceUrl: "https://iari.res.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "Krishi Vigyan Kendra (KVK) Punjab Agricultural University",
    type: "KVK",
    address: "Punjab Agricultural University Campus, Ferozepur Road, Ludhiana, Punjab 141004",
    district: "Ludhiana",
    state: "Punjab",
    pincode: "141004",
    phone: "0161-2401960",
    email: "kvkludhiana@pau.edu",
    website: "https://pau.edu",
    location: {
      type: "Point" as const,
      coordinates: [75.8078, 30.9010],
    },
    officialSource: "Punjab Agricultural University / ICAR",
    sourceUrl: "https://pau.edu",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "Krishi Vigyan Kendra (KVK) National Dairy Research Institute",
    type: "KVK",
    address: "ICAR - NDRI Campus, GT Road, Karnal, Haryana 132001",
    district: "Karnal",
    state: "Haryana",
    pincode: "132001",
    phone: "0184-2259023",
    email: "kvkndri@gmail.com",
    website: "https://ndri.res.in",
    location: {
      type: "Point" as const,
      coordinates: [76.9905, 29.6981],
    },
    officialSource: "ICAR - National Dairy Research Institute",
    sourceUrl: "https://ndri.res.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "Krishi Vigyan Kendra (KVK) Anand Agricultural University",
    type: "KVK",
    address: "Anand Agricultural University Campus, Anand, Gujarat 388110",
    district: "Anand",
    state: "Gujarat",
    pincode: "388110",
    phone: "02692-262145",
    email: "kvkanand@aau.in",
    website: "https://aau.in",
    location: {
      type: "Point" as const,
      coordinates: [72.9324, 22.5539],
    },
    officialSource: "Anand Agricultural University / ICAR",
    sourceUrl: "https://aau.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "Krishi Vigyan Kendra (KVK) University of Agricultural Sciences Bengaluru",
    type: "KVK",
    address: "GKVK Campus, Bellary Road, Bengaluru, Karnataka 560065",
    district: "Bengaluru Rural",
    state: "Karnataka",
    pincode: "560065",
    phone: "080-23620358",
    email: "kvkbengaluru@uasbangalore.edu.in",
    website: "https://uasbangalore.edu.in",
    location: {
      type: "Point" as const,
      coordinates: [77.5772, 13.0784],
    },
    officialSource: "University of Agricultural Sciences, Bengaluru / ICAR",
    sourceUrl: "https://uasbangalore.edu.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "Krishi Vigyan Kendra (KVK) Banaras Hindu University",
    type: "KVK",
    address: "Institute of Agricultural Sciences, BHU Campus, Varanasi, Uttar Pradesh 221005",
    district: "Varanasi",
    state: "Uttar Pradesh",
    pincode: "221005",
    phone: "0542-2368993",
    email: "kvk.bhu@gmail.com",
    website: "https://bhu.ac.in",
    location: {
      type: "Point" as const,
      coordinates: [82.9913, 25.2677],
    },
    officialSource: "Institute of Agricultural Sciences, BHU / ICAR",
    sourceUrl: "https://kvk.icar.gov.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
  {
    name: "Government District Soil Testing Laboratory Lucknow",
    type: "SoilLab",
    address: "Krishi Bhawan Campus, Madan Mohan Malviya Marg, Lucknow, Uttar Pradesh 226001",
    district: "Lucknow",
    state: "Uttar Pradesh",
    pincode: "226001",
    phone: "0522-2207641",
    email: "",
    website: "https://soilhealth.dac.gov.in",
    location: {
      type: "Point" as const,
      coordinates: [80.9462, 26.8467],
    },
    officialSource: "Department of Agriculture, Govt of Uttar Pradesh / Soil Health Card Portal",
    sourceUrl: "https://soilhealth.dac.gov.in",
    isVerified: true,
    lastVerified: new Date("2026-01-15"),
  },
];

export async function ensureAgricultureCentersSeeded() {
  try {
    await connectDB();
    const count = await AgricultureCenter.countDocuments();
    if (count === 0) {
      console.log("Seeding verified agriculture support centers catalog...");
      await AgricultureCenter.insertMany(VERIFIED_AGRICULTURE_CENTERS);
      console.log(`Successfully seeded ${VERIFIED_AGRICULTURE_CENTERS.length} verified agriculture centers.`);
    }
  } catch (error) {
    console.error("Error seeding agriculture centers:", error);
  }
}
